### ISSUE TITLE
libre.sh :)

### ISSUE THREAD

**Issue by pierreozoux** [puffinrocks/apps#1]
Arf! We missed each other!

https://fosdem.org/2017/schedule/event/puffin/

just a little ping to say, that puffin looks as a great frontend for libre.sh :)

We also have a catalog of docker-compose, and this would be nice to share the work and maintenance there!

And also another quick question, what do you think about k8s?

**Comment by loomchild** [comment]
Hi, 

Yes, I know:) 

I really wanted to meet you at FOSDEM, but had so much to do on Saturday and prepared the presentation until the last minute on Sunday, that it didn't work out.. Never mind, we can communicate online and meet during next occasion.

I am following IndieHosters and recently discovered libre.sh - will try it soon. True we should think about a way to share the apps in store - let's compare the app package formats and see what we can do.

About Kubernetes... Yes, I am considering to use it instead of pure Docker to minimize the amount of work, because it does a lot of things out of the box. However, on the other hand I like to have access to the latest features directly on Docker and Docker-Compose (BTW do you know what's the Kubernetes counterpart of it?), since I think it's sufficiently high-level. I was also considering using Rancher as a back-end. What's your opinion about Kubernetes, do you want to migrate to it?

**Comment by loomchild** [comment]
Hi,

I see that you are putting money where your mouth is and working hard on Kubernetes :) I am still not 100% convinced that I need it to run small / individual applications, although seems like most of the world, including cloud providers and platforms, is switching to it.

I will close this issue, I hope it's OK. Feel free to continue the discussion about Kubernetes [here](https://github.com/puffinrocks/puffin/issues/12).

Are you coming to FOSDEM 2018? Perhaps we can meet for a beer or during Decentralized Internet track?

BTW, feel free to check out [Sojourner](https://sojourner.loomchild.net/) conference planner - my first PWA or in general purely front-end project:)

**Comment by loomchild** [comment]
Hi,

I see that you are putting money where your mouth is and working hard on Kubernetes :) I am still not 100% convinced that I need it to run small / individual applications, although seems like most of the world, including cloud providers and platforms, is switching to it.

I will close this issue, I hope it's OK. Feel free to continue the discussion about Kubernetes [here](https://github.com/puffinrocks/puffin/issues/12).

Are you coming to FOSDEM 2018? Perhaps we can meet for a beer or during Decentralized Internet track?

BTW, feel free to check out [Sojourner](https://sojourner.loomchild.net/) conference planner - my first PWA or in general purely front-end project:)
