### ISSUE TITLE
Stop starting a DB instance for each app

### ISSUE THREAD

**Issue by boramalper** [puffinrocks/apps#3]
`db` service is defined separately in each docker-compose.yml (see ttrss, wallabag, and wordpress for example). Correct me if I am wrong, but I think this starts running a db engine *for each app*, which is quite inefficient.

I think a solution would be to [share compose configuration between apps](https://docs.docker.com/compose/extends/) to abstract common services out.

Since we also use both PostgreSQL *and* MariaDB (which is not necessary), we might as well stick to MariaDB for all apps for reduced complexity + efficiency.

I'd be happy to send some PRs if you agree.

**Comment by loomchild** [comment]
Hi, you are correct that it's starting a DB for each service.

However, I want to keep it this way to keep the applications independent. Otherwise changes, bug or increased traffic in one application can affect the others, and I'd like to avoid that. Also different applications can use different type or version of DB (PostrgreSQL is not the same as MySQL and there are differences between versions or installed plugins.) I want to give application developers maximum freedom when choosing storage mechanism and software they want to run to make it easier to add new applications to the catalog.

So far I haven't had any issues with performance despite running hundred applications on a single machine. The way to optimize it could be to configure individual databases to be lighter (in terms of memory usage for example) as in general each Puffin application is supposed to serve only one user or small group of users. What you are proposing is closer to the cloud model (AWS, etc.), which could be very efficient when running lots of applications, but not really the direction I'd like to go.

**Comment by loomchild** [comment]
Perhaps, could you start by stating what problem are you trying to solve? Is Puffin too heavy (cpu, memory-wise) for some devices (rasperry pi) or hosting providers?

**Comment by boramalper** [comment]
Oh no I haven't encountered any problems myself, but I was just checking the apps and thought it might be problematic.

I'm closing the issue then. =)
